version: '3.8'

services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=Akashi
      - POSTGRES_PASSWORD=Aymane1337
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
        - 8080:80
    restart: always
    volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
        - 'host.docker.internal:host-gateway'


volumes:
  postgres:
